#!/bin/sh
DIRNAME=`dirname "$0"`
PROJECTDIR=$1
# Setup the JVM
if [ "x$JAVA" = "x" ]; then
    if [ "x$JAVA_HOME" != "x" ]; then
        JAVA="$JAVA_HOME/bin/java"
    else
        JAVA="java"
    fi
fi

# Check if a directory parameter was given
if [ -z "$PROJECTDIR" ]; then
    PROJECTDIR=`pwd`
fi

echo "Java version: $JAVA"
java -jar $DIRNAME/tycho-version-sync.jar $PROJECTDIR
